context("data access")

test_that("DNA can use databases and profiles", {
  testthat::skip_on_cran()
  testthat::skip_on_ci()
  jar <- dna_jar()
  expect_message(dna_jar(), "Jar file found")
  expect_message(dna_init(), "DNA connection established")
  s <- dna_sample()
  expect_equal(dim(dna_queryCoders("sample.dna")), c(4, 3))
  expect_false(dna_openDatabase(db_url = s, coderId = 12, coderPassword = "sample"))
  expect_false(dna_openDatabase(db_url = s, coderId = 2, coderPassword = "test"))
  expect_error(dna_openDatabase(db_url = "test.dna", coderId = 2, coderPassword = "sample"), "Database file not found")
  expect_output(dna_openDatabase(db_url = s, coderId = 2, coderPassword = "sample"), "DNA database: ")
  expect_output(dna_printDetails(), "DNA database: ")
  expect_output(dna_printDetails(), "41 statements in 7 documents")
  expect_false(dna_saveConnectionProfile(file = "profile.dnc", coderPassword = "sample"))
  expect_false(dna_saveConnectionProfile(file = "profile.dnc", coderPassword = "sample"))
  expect_output(dna_closeDatabase(), "Database was closed")
  expect_output(dna_closeDatabase(), "Tried to close database, but none was open")
  expect_false(dna_saveConnectionProfile(file = "profile2.dnc", coderPassword = "sample"))
  expect_error(dna_openConnectionProfile(file = "profile2.dnc", coderPassword = ""), "File does not exist")
  expect_false(dna_openConnectionProfile(file = "profile.dnc", coderPassword = "test"))
  expect_output(dna_openConnectionProfile(file = "profile.dnc", coderPassword = "sample"), "DNA database: ")
  unlink("profile.dnc")
})

test_that("dna_sample works", {
  unlink("sample.dna")
  expect_equal(dna_sample(), paste0(getwd(), "/sample.dna"))
  expect_true(file.exists(paste0(getwd(), "/sample.dna")))
  expect_gt(file.size(paste0(getwd(), "/sample.dna")), 200000)
  expect_warning(dna_sample(), "Sample file already exists")
  unlink("sample.dna")
})