context("data access")

suppressPackageStartupMessages(library("rDNA"))
jar <- dna_jar()

test_that("DNA can use databases and profiles", {
  expect_message(dna_jar(), "Jar file found")
  expect_message(dna_init(), "DNA connection established")
  s <- dna_sample()
  expect_equal(dim(dna_queryCoders("sample.dna")), c(4, 3))
  expect_output(dna_openDatabase(coderId = 12, coderPassword = "sample", db_url = s), "Failed to authenticate coder 12")
  expect_output(dna_openDatabase(coderId = 2, coderPassword = "test", db_url = s), "Failed to authenticate coder 2")
  expect_error(dna_openDatabase(coderId = 2, coderPassword = "sample", db_url = "test.dna"), "Database file not found")
  expect_output(dna_openDatabase(coderId = 2, coderPassword = "sample", db_url = s), "DNA database: ")
  expect_output(dna_printDetails(), "DNA database: ")
  expect_output(dna_printDetails(), "41 statements in 7 documents")
  expect_output(dna_saveConnectionProfile(file = "profile.dnc", coderPassword = "sample"), "Connection profile saved to file")
  expect_output(dna_saveConnectionProfile(file = "profile.dnc", coderPassword = "sample"), "File already exists and will not be overwritten")
  expect_output(dna_closeDatabase(), "Database was closed")
  expect_output(dna_closeDatabase(), "Tried to close database, but none was open")
  expect_output(dna_saveConnectionProfile(file = "profile2.dnc", coderPassword = "sample"), "No database open. Could not save connection profile")
  expect_error(dna_openConnectionProfile(file = "profile2.dnc", coderPassword = ""), "File does not exist")
  expect_output(dna_openConnectionProfile(file = "profile.dnc", coderPassword = "test"), "Connection profile could not be decrypted")
  expect_output(dna_openConnectionProfile(file = "profile.dnc", coderPassword = "sample"), "DNA database: ")

})

test_that("dna_sample works", {
  unlink("sample.dna")
  expect_equal(dna_sample(), paste0(getwd(), "/sample.dna"))
  expect_true(file.exists(paste0(getwd(), "/sample.dna")))
  expect_gt(file.size(paste0(getwd(), "/sample.dna")), 200000)
  expect_warning(dna_sample(), "Sample file already exists")
  unlink("sample.dna")
})