name: build

on: [push, pull_request, workflow_dispatch]

jobs:
  Bibliography:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: r-lib/actions/setup-tinytex@v2

    - name: Install LaTeX packages
      run: tlmgr install urlbst

    - uses: gradle/wrapper-validation-action@v1
    - uses: actions/cache@v3
      id: pandoc
      with:
        path: pandoc-2.19.2-1
        key: pandoc-2.19.2-1
    - name: Download pandoc-2.19.2-1-amd64.deb
      if: steps.pandoc.outputs.cache-hit != 'true'
      run: |
        mkdir pandoc-2.19.2-1
        cd pandoc-2.19.2-1
        wget https://github.com/jgm/pandoc/releases/download/2.19.2/pandoc-2.19.2-1-amd64.deb
    - name: Install pandoc
      run: |
        cd pandoc-2.19.2-1
        sudo dpkg -i pandoc-2.19.2-1-amd64.deb

    - name: Check pandoc version
      run: pandoc --version

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.4.2

    - name: Execute Gradle build for bibliography
      run: ./gradlew :bibliography:build

    - name: Store artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Bibliography
        path: build/bibliography.*

  DNA:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: gradle/wrapper-validation-action@v1
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        cache: gradle

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.4.2
    
    - name: Execute Gradle build for DNA
      run: ./gradlew :dna:build
    
    - name: Store artifacts
      uses: actions/upload-artifact@v3
      with:
        name: DNA
        path: build/*.jar

  rDNA:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: r-lib/actions/setup-r@v2

    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        cache-version: 2
        working-directory: rDNA/rDNA
        extra-packages: |
          any::ggplot2
          any::roxygen2
          any::igraph
          any::ggraph
          any::askpass
          any::cluster
          any::sna

    - uses: gradle/wrapper-validation-action@v1

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.4.2

    - name: Execute Gradle build for rDNA
      run: ./gradlew :rDNA:build

    - name: Store artifacts
      uses: actions/upload-artifact@v3
      with:
        name: rDNA
        path: build/*.tar.gz

  rDNA-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'oldrel-1'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
          working-directory: rDNA/rDNA

      - uses: r-lib/actions/check-r-package@v2
        with:
          working-directory: rDNA/rDNA
          upload-snapshots: true
