name: Matrix message

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  send-message:
    runs-on: ubuntu-latest
    name: Send message via Matrix
    steps:
    - name: Send message to DNA Matrix space development room
      id: matrix-chat-message
      uses: fadenb/matrix-chat-message@v0.0.6
      with:
        homeserver: ${{ secrets.MATRIX_SERVER }}
        token: ${{ secrets.MATRIX_TOKEN }}
        channel: ${{ secrets.MATRIX_ROOM_ID }}
        message: |
          New [commit](https://github.com/leifeld/dna/commit/${{ github.sha }}) in the [dna](https://github.com/leifeld/dna/) GitHub repository (branch: ${{ github.ref_name }}). Commit message: ${{ github.event.head_commit.message }}.
